version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: debug
      POSTGRES_PASSWORD: debug
    ports:
      - "5432:5432"

  redis:
    image: redis:7