ACCESS_TOKEN_EXPIRE_MINUTES = 15  # 15 minutes
REFRESH_TOKEN_EXPIRE_MINUTES = 60 * 24 * 7  # 7 days
ALGORITHM = "HS256"

# Game
GAME_LAUNCH_PERIOD = 2  # 2 hours

# map
MAP_WIDTH = 100
MAP_HEIGHT = 100
MAP_BLOCK_SEEDS_AMOUNT = 10
MAP_BLOCK_GROWTH_RATE = 50
MAP_WALL_SEEDS_AMOUNT = 30
MAP_WALL_GROWTH_RATE = 30
MAP_GRASS_SEEDS_AMOUNT = 30
MAP_GRASS_GROWTH_RATE = 10
MAP_TUNNEL_SEEDS_AMOUNT = 10
MAP_TUNNEL_GROWTH_RATE = 0
MAP_PIT_SEEDS_AMOUNT = 30
MAP_PIT_GROWTH_RATE = 0
MAP_THORN_SEEDS_AMOUNT = 10
MAP_THORN_GROWTH_RATE = 10

MAPPOS_TYPE_BLOCK = 0
MAPPOS_TYPE_WALL = 1
MAPPOS_TYPE_GRASS = 2
MAPPOS_TYPE_TUNNEL = 3
MAPPOS_TYPE_PIT = 4
MAPPOS_TYPE_THORN = 5
