ACCESS_TOKEN_EXPIRE_MINUTES = 60 * 24  # 1 day
REFRESH_TOKEN_EXPIRE_MINUTES = 60 * 24 * 7  # 7 days
ALGORITHM = "HS256"

# Game
GAME_LAUNCH_PERIOD = 2  # Every 2 hours
GAME_COUNTDWON_TIME = 10  # 10 minutes

# item box
HIGH_ITEMBOX_COUNT = 1
MEDIUM_ITEMBOX_COUNT = 3
LOW_ITEMBOX_COUNT = 6

# Job
DEFAULT_ALLOW_GOLD = 100
DEFAULT_SPEED = 20

# Score
SCORES_PER_BOX = [3, 6, 10]
