"""Create TokenTable model

Revision ID: 038ee3f22c3f
Revises: 2f910007aef6
Create Date: 2024-02-23 16:59:44.516200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '038ee3f22c3f'
down_revision: Union[str, None] = '2f910007aef6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('access_toke', sa.String(length=450), nullable=False),
    sa.Column('refresh_toke', sa.String(length=450), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('access_toke')
    )
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('user_item_log', sa.Column('created', sa.DateTime(), nullable=False))
    op.add_column('user_item_log', sa.Column('updated', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_item_log', 'updated')
    op.drop_column('user_item_log', 'created')
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('token')
    # ### end Alembic commands ###
