"""update user model

Revision ID: 04da5d0d403f
Revises: d727825689c4
Create Date: 2024-02-20 12:24:15.065477

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "04da5d0d403f"
down_revision: Union[str, None] = "d727825689c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("updated", sa.DateTime(), nullable=False))
    op.alter_column("user", "user_name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "user", "created", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "created", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column("user", "user_name", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("user", "updated")
    # ### end Alembic commands ###
