"""update game_money column

Revision ID: 1fa67f27285b
Revises: fe1fb9bf4d71
Create Date: 2024-04-04 13:48:11.476328

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1fa67f27285b"
down_revision: Union[str, None] = "fe1fb9bf4d71"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "game_money", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "game_money", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
