"""Create user_item_log model

Revision ID: 2f910007aef6
Revises: da9e9a88b250
Create Date: 2024-02-20 15:48:22.757260

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2f910007aef6"
down_revision: Union[str, None] = "da9e9a88b250"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_item_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("picked_date", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("item_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["item.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_item_log_id"), "user_item_log", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_item_log_id"), table_name="user_item_log")
    op.drop_table("user_item_log")
    # ### end Alembic commands ###
