"""update user model with job id

Revision ID: 32c6f0ee9f0a
Revises: fce1004f0037
Create Date: 2024-04-01 20:04:41.595197

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "32c6f0ee9f0a"
down_revision: Union[str, None] = "fce1004f0037"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
