"""add enabled field in job model

Revision ID: 334d00f3d164
Revises: 67308a293c7b
Create Date: 2024-05-07 22:41:02.890452

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "334d00f3d164"
down_revision: Union[str, None] = "67308a293c7b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("job", sa.Column("enabled", sa.Boolean()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("job", "enabled")
    # ### end Alembic commands ###
