"""Update item model

Revision ID: 3546bd87018f
Revises: 237cbce2f77e
Create Date: 2024-04-02 19:00:31.329365

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3546bd87018f"
down_revision: Union[str, None] = "237cbce2f77e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("item", sa.Column("hp", sa.Integer(), nullable=True))
    op.add_column("item", sa.Column("sp", sa.Integer(), nullable=True))
    op.add_column("item", sa.Column("duration", sa.Integer(), nullable=True))
    op.add_column("item", sa.Column("group", sa.Text(), nullable=False))
    op.add_column("item", sa.Column("function", sa.Integer(), nullable=False))
    op.add_column("item", sa.Column("description", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("item", "description")
    op.drop_column("item", "function")
    op.drop_column("item", "group")
    op.drop_column("item", "duration")
    op.drop_column("item", "sp")
    op.drop_column("item", "hp")
    # ### end Alembic commands ###
