"""update skill

Revision ID: 3c1b6dfb4598
Revises: 991fa8855718
Create Date: 2024-04-03 09:31:00.125912

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3c1b6dfb4598"
down_revision: Union[str, None] = "991fa8855718"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("skill", sa.Column("job_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("skill", "job_id")
    # ### end Alembic commands ###
