"""add job type in item model

Revision ID: 3f2cf02fa804
Revises: 12fb55233255
Create Date: 2024-04-14 23:09:56.078625

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3f2cf02fa804"
down_revision: Union[str, None] = "12fb55233255"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("item", sa.Column("job_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "item", "job", ["job_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "item", type_="foreignkey")
    op.drop_column("item", "job_id")
    # ### end Alembic commands ###
