"""add start_date and end_date in notice

Revision ID: 592543b549a8
Revises: eb8eaadfbd7c
Create Date: 2024-07-08 12:10:06.491887

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "592543b549a8"
down_revision: Union[str, None] = "eb8eaadfbd7c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("notice", sa.Column("start_date", sa.Date(), nullable=True))
    op.add_column("notice", sa.Column("end_date", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("notice", "end_date")
    op.drop_column("notice", "start_date")
    # ### end Alembic commands ###
