"""update job and add skill

Revision ID: 991fa8855718
Revises: 545c96ff4234
Create Date: 2024-04-03 09:21:48.298719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '991fa8855718'
down_revision: Union[str, None] = '545c96ff4234'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('attributes', sa.Text(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_id'), 'skill', ['id'], unique=False)
    op.add_column('job', sa.Column('allow_gold', sa.Integer(), nullable=False))
    op.add_column('job', sa.Column('speed', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'speed')
    op.drop_column('job', 'allow_gold')
    op.drop_index(op.f('ix_skill_id'), table_name='skill')
    op.drop_table('skill')
    # ### end Alembic commands ###
