"""add notification name

Revision ID: eb8eaadfbd7c
Revises: 334d00f3d164
Create Date: 2024-07-06 22:06:26.876351

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eb8eaadfbd7c"
down_revision: Union[str, None] = "334d00f3d164"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notice", sa.Column("name", sa.String(), nullable=False, server_default="Alarm")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("notice", "name")
    # ### end Alembic commands ###
