"""make item_id as unique key in shop model

Revision ID: fe1fb9bf4d71
Revises: 3c1b6dfb4598
Create Date: 2024-04-04 08:02:55.002580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe1fb9bf4d71'
down_revision: Union[str, None] = '3c1b6dfb4598'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'shop', ['item_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shop', type_='unique')
    # ### end Alembic commands ###
